### ISSUE TITLE
Compiling Stochastic solver returns linking errors

### ISSUE THREAD

**Issue by preoteasa** [rishabhs/sygus-comp14#1]
I have tried to compile the Stochastic solver with different versions of g++ and with different versions of z3, but all give many linking errors related to 
Z3_mk_int_sort, Z3_dec_ref, ...

I tried compiling it under Ubuntu 12.04 64 bit using g++ 4.6.4, g++ 4.8.1. I also tried a pre-compiled version of z3, I tried the version included with enumerative solvers, and I tried a version of z3 compiled from sources.

Best regards,

Viorel Preoteasa

**Comment by abhishekudupa** [comment]
Marking as closed
