### ISSUE TITLE
How to set depth of exploration for enumerative solver?

### ISSUE THREAD

**Issue by heldib** [rishabhs/sygus-comp14#3]
Does there exist an option for specifying the allowed depth of exploration? 
For the bellow benchmark, there exists a solution at depth 3. The enumerative solver returns "No Solutions!", while the symbolic solver is able to find the valid solution.

I think the allowed depth of exploration is the problem because if the solution is at a depth of less than 3, the enumerative solver would find it.

(set-logic BV)

(define-fun hd10 (      (y Bool) (z Bool)    ) Bool ( and y z)          )

(synth-fun f ( (y Bool) (z Bool))    Bool
    ((Start Bool (
		                                  (and depth1 depth1)
						   ))
    (depth1 Bool (
		                                  (and depth2 depth2)
						   ))
    (depth2 Bool (
		                                  (and depth3 depth3)
						   ))
    (depth3 Bool (				   
						   y
						   z)))
)

(declare-var y Bool)
(declare-var z Bool)
(constraint (= (hd10  y z) (f  y z)))
(check-synth)

**Comment by abhishekudupa** [comment]
Hassan,

The enumerative solver does not allow you to specify the depth it explores
to. Instead, it allows you to specify the SIZE of the expression. In the
case that you have mentioned, the enumerative solver finds a solution of
size 15. Please run the enumerative solver with the --help argument to get
a list of options, etc.

Hope that helps.

Best,
Abhishek

**Comment by abhishekudupa** [comment]
Closed, as no change. The enumerative solver works on expression sizes, not on depth of expression. Please open a new bug as a request for feature, if this feature is essential for you
